### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/hml-validation-portal#3]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.812 s
[INFO] Finished at: 2020-04-23T15:37:06-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hml-validation-portal: Could not resolve dependencies for project org.nmdp:hml-validation-portal:jar:1.0-SNAPSHOT: Could not find artifact org.nmdp.b12s.mac:mac-client:jar:0.54 in central (https://repo.maven.apache.org/maven2)

**Comment by ambarishK** [comment]
Same error is with me also.
````
Failure to find org.nmdp.b12s.mac:mac-client:jar:0.54 in https://repo.maven.apache.org/maven2

````
Please resolve.

**Comment by ambarishK** [comment]
Hello JAY!
Could you resolve the error?

**Comment by jiyer-nmdp** [comment]
Created a PR for this and have asked for reviews.

**Comment by jiyer-nmdp** [comment]
Code is updated. Reviewed and Merged on Friday

**Comment by jiyer-nmdp** [comment]
Can this issue be closed?

**Comment by ambarishK** [comment]
Let me check.

**Comment by ambarishK** [comment]
Hello Jay!

I am getting another error into class - hmlInputController

````
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-05-03 00:37:02.241 ERROR 7040 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hmlInputController' defined in file [/home/ngsap2/hml-validation-portal/target/classes/org/nmdp/controller/HmlInputController.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.nmdp.controller.HmlInputController]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems: 
	The import io.swagger.api cannot be resolved
	HmlApi cannot be resolved to a type

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1303) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1197) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.nmdp.startup.ServiceHmlValidationPortal.main(ServiceHmlValidationPortal.java:17) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.nmdp.controller.HmlInputController]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems: 
	The import io.swagger.api cannot be resolved
	HmlApi cannot be resolved to a type

	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1295) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	... 17 common frames omitted
Caused by: java.lang.Error: Unresolved compilation problems: 
	The import io.swagger.api cannot be resolved
	HmlApi cannot be resolved to a type

	at org.nmdp.controller.HmlInputController.<init>(HmlInputController.java:7) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_252]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_252]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_252]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_252]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	... 19 common frames omitted
````

**Comment by ambarishK** [comment]
Above error is due to import of interface. JAVA class corresponding the interface is unable to locate.
````
import io.swagger.api.hml.HmlApi;
````

**Comment by jiyer-nmdp** [comment]
HmlApi is an auto generated class. Let me investigate why its failing. Thank you for letting me know Ambarish.

**Comment by ambarishK** [comment]
Most welcome.

Waiting for updates.
